
-- Add GST fields to invoices
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS gst_percentage numeric DEFAULT 18;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS gst_amount numeric DEFAULT 0;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS subtotal numeric DEFAULT 0;

-- Notification logs table
CREATE TABLE public.notification_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL REFERENCES public.studios(id) ON DELETE CASCADE,
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  job_id uuid REFERENCES public.jobs(id) ON DELETE SET NULL,
  invoice_id uuid REFERENCES public.invoices(id) ON DELETE SET NULL,
  channel text NOT NULL DEFAULT 'whatsapp',
  template_type text NOT NULL,
  recipient_phone text,
  recipient_name text,
  message_body text NOT NULL,
  status text NOT NULL DEFAULT 'sent',
  metadata jsonb DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Studio members can view notification logs"
  ON public.notification_logs FOR SELECT TO authenticated
  USING (studio_id IN (SELECT studio_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Studio members can insert notification logs"
  ON public.notification_logs FOR INSERT TO authenticated
  WITH CHECK (studio_id IN (SELECT studio_id FROM public.profiles WHERE user_id = auth.uid()));

-- Notification templates table
CREATE TABLE public.notification_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  studio_id uuid REFERENCES public.studios(id) ON DELETE CASCADE,
  template_type text NOT NULL,
  channel text NOT NULL DEFAULT 'whatsapp',
  title text NOT NULL,
  body_template text NOT NULL,
  is_default boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read default templates"
  ON public.notification_templates FOR SELECT TO authenticated
  USING (is_default = true OR studio_id IN (SELECT studio_id FROM public.profiles WHERE user_id = auth.uid()));

CREATE POLICY "Studio members can manage templates"
  ON public.notification_templates FOR ALL TO authenticated
  USING (studio_id IN (SELECT studio_id FROM public.profiles WHERE user_id = auth.uid()))
  WITH CHECK (studio_id IN (SELECT studio_id FROM public.profiles WHERE user_id = auth.uid()));

-- Insert default templates
INSERT INTO public.notification_templates (studio_id, template_type, channel, title, body_template, is_default) VALUES
  (NULL, 'job_started', 'whatsapp', 'Job Started', 'Hi {{customer_name}}, work has started on your {{car_make}} {{car_model}} ({{registration}}) at {{studio_name}}. Track progress: {{track_link}}', true),
  (NULL, 'job_completed', 'whatsapp', 'Job Completed', 'Hi {{customer_name}}, your {{car_make}} {{car_model}} is ready for pickup at {{studio_name}}! Total: ₹{{total_price}}', true),
  (NULL, 'invoice_sent', 'whatsapp', 'Invoice Sent', 'Hi {{customer_name}}, invoice {{invoice_number}} for ₹{{amount}} has been generated by {{studio_name}}. Due: {{due_date}}', true),
  (NULL, 'estimate_sent', 'whatsapp', 'Estimate Sent', 'Hi {{customer_name}}, {{studio_name}} has sent you an estimate of ₹{{grand_total}} for your {{car_make}} {{car_model}}. Valid until {{valid_until}}.', true);
